import React, { useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { useAppDispatch } from "../../state/store.ts";
import { verifyOtp } from "../../state/auth/thunk.ts";
import { Button, TextField, Container, Typography, Box, Card, CardContent } from '@mui/material';
import { Helmet } from "react-helmet-async";

const VerifyOtp = () => {
    const location = useLocation();
    const navigate = useNavigate();
    const dispatch = useAppDispatch();

    const [otp, setOtp] = useState('');
    const username = location.state?.username;

    const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
        event.preventDefault();

        if (!username) {
            console.error('Username is missing!');
            return;
        }

        try {
            await dispatch(verifyOtp({ code: otp, username })).unwrap();
            navigate('/');
        } catch (error) {
            console.error('OTP verification failed:', error);
        }
    };

    const isOtpValid = otp.length === 6;

    return (
        <>
            <Helmet>
                <title>Verify OTP | Lab Management IT</title>
            </Helmet>
            <Box
                sx={{
                    display: 'flex',
                    justifyContent: 'center',
                    alignItems: 'center',
                    minHeight: '100vh',
                    backgroundColor: 'background.default',
                }}
            >
                <Container maxWidth="sm">
                    <Card sx={{ borderRadius: 3, boxShadow: theme => theme.shadows[5], backgroundColor: 'background.paper' }}>
                        <CardContent>
                            <Typography variant="h4" align="center" sx={{ marginBottom: 3, fontWeight: 'bold', color: 'text.primary' }}>
                                Two-Factor Authentication
                            </Typography>
                            <Typography variant="body1" align="center" sx={{ marginBottom: 3, color: 'text.secondary' }}>
                                Enter the 6-digit validation code generated by your authentication app
                            </Typography>
                            <form onSubmit={handleSubmit}>
                                <TextField
                                    label="OTP Code"
                                    variant="outlined"
                                    fullWidth
                                    type="text"
                                    value={otp}
                                    onChange={(e) => setOtp(e.target.value)}
                                    placeholder="Enter OTP code"
                                    sx={{ marginBottom: 3 }}
                                    slotProps={{
                                        htmlInput: {
                                            maxLength: 6
                                        }
                                    }}
                                />

                                <Button
                                    variant="contained"
                                    type="submit"
                                    fullWidth
                                    disabled={!isOtpValid}
                                    sx={{
                                        color: (!otp || otp.length !== 6) ? 'grey.600' : 'primary.contrastText',
                                        "&:disabled": {
                                            backgroundColor: 'grey.400',
                                            color: 'grey.600',
                                        }
                                    }}
                                >
                                    Verify
                                </Button>
                            </form>
                            <Box sx={{ marginTop: 2, textAlign: 'center' }}>
                                <Typography variant="body2">
                                    <Link
                                        to={`/account/verify-email?username=${encodeURIComponent(username)}`}
                                        style={{color: '#1976d2', textDecoration: 'none', fontWeight: 'bold'}}
                                    >
                                        Using another way to verify
                                    </Link>
                                </Typography>
                            </Box>
                        </CardContent>
                    </Card>
                </Container>
            </Box>
        </>
    );
};

export default VerifyOtp;